#!/usr/bin/env python


IZZI_STATUS_MESSAGE_ID = 0x63

IZZI_STATUS_MSG_ID_INDEX = 0
IZZI_STATUS_MSG_OUTDOR_AIR_TEMP_INDEX = 1
IZZI_STATUS_MSG_EXHAUST_AIR_TEMP_INDEX = 2
IZZI_STATUS_MSG_SUPPLY_AIR_TEMP_INDEX = 3
IZZI_STATUS_MSG_EXTRACT_AIR_TEMP_INDEX = 4
IZZI_STATUS_MSG_COVER_STATE_INDEX = 5
IZZI_STATUS_MSG_DEFROST_STATE_INDEX = 6
IZZI_STATUS_MSG_BYPASS_STATE_INDEX = 8
IZZI_STATUS_MSG_HIGRO_CO2_STATUS_INDEX = 9
IZZI_STATUS_MSG_HUMIDITY_STATE_INDEX = 15
IZZI_STATUS_MSG_PPM_STATE_INDEX = 16
IZZI_STATUS_MSG_CF_EXHAUST_SPEED_STATE_INDEX = 17
IZZI_STATUS_MSG_CF_SUPPLY_SPEED_STATE_INDEX = 18

IZZI_STATUS_MSG_BYPASS_STATE_CLOSED = 0
IZZI_STATUS_MSG_BYPASS_STATE_OPEN = 1

IZZI_STATUS_MSG_HIGRO_CO2_STATE_OFF = 1
IZZI_STATUS_MSG_HIGRO_CO2_STATE_ON = 2

IZZY_STATUS_MSG_DEFROST_STATE_ACTIVE = 10
IZZY_STATUS_MSG_COVER_STATE_OPEN = 5
IZZY_STATUS_MSG_COVER_STATE_CLOSED = 0

IZZI_COMMAND_MESSAGE_ID = 0x64

IZZI_CMD_MSG_ID_INDEX = 0
IZZI_CMD_MSG_BYPASS_TEMP_INDEX = 8
IZZI_CMD_MSG_BYPASS_MODE_INDEX = 9
IZZI_CMD_MSG_SUPPLY_FAN_SPEED_INDEX = 10
IZZI_CMD_MSG_EXTRACT_FAN_SPEED_INDEX = 11
IZZI_CMD_MSG_UNIT_STATE_INDEX = 12
IZZI_CMD_MSG_CURRENT_VENT_MODE_INDEX = 16
IZZI_CMD_MSG_HIGRO_CO2_STATE_INDEX = 18
IZZI_CMD_MSG_SUPPLY_STATE_INDEX = 19
IZZI_CMD_MSG_EXTRACT_STATE_INDEX = 20

IZZY_CMD_BYPASS_MODE_AUTO = 0
IZZY_CMD_BYPASS_MODE_OPEN = 1
IZZY_CMD_BYPASS_MODE_CLOSED = 2

IZZI_CMD_NEW_VENT_MODE_OFF = 0
IZZI_CMD_NEW_VENT_MODE_SPEED_1 = 1
IZZI_CMD_NEW_VENT_MODE_SPEED_2 = 2
IZZI_CMD_NEW_VENT_MODE_SPEED_3 = 3
IZZI_CMD_NEW_VENT_MODE_VENT_MAX = 4
IZZI_CMD_NEW_VENT_MODE_FIREPLACE = 5
IZZI_CMD_NEW_VENT_MODE_AWAY = 6
IZZI_CMD_NEW_VENT_MODE_AUTO = 7

IZZY_CMD_UNIT_STATE_ON = 0
IZZY_CMD_UNIT_STATE_OFF = 1

IZZY_CMD_SUPPLY_STATE_OFF = 1
IZZY_CMD_SUPPLY_STATE_ON = 0
IZZY_CMD_EXTRACT_STATE_OFF = 1
IZZY_CMD_EXTRACT_STATE_ON = 0

IZZY_SENSOR_VENT_MODE_NONE = 0
IZZY_SENSOR_VENT_MODE_FIREPLACE = 1
IZZY_SENSOR_VENT_MODE_OPEN_WINDOW = 2
IZZY_SENSOR_VENT_MODE_COOKER_HOOD = 3

IZZY_SENSOR_FAN_EXTRACT_SPEED_ID = 0x01
IZZY_SENSOR_FAN_SUPPLY_SPEED_ID = 0x02
IZZY_SENSOR_TEMPERATURE_SUPPLY_ID = 0x03
IZZY_SENSOR_TEMPERATURE_EXTRACT_ID = 0x04
IZZY_SENSOR_TEMPERATURE_EXHAUST_ID = 0x05
IZZY_SENSOR_TEMPERATURE_OUTDOOR_ID = 0x06
IZZY_SENSOR_BYPASS_STATE_ID = 0x07
IZZY_SENSOR_FAN_MODE_ID = 0x08
IZZY_SENSOR_UNIT_STATE_ID = 0x09
IZZY_SENSOR_BYPASS_TEMP_ID = 0x0A
IZZY_SENSOR_BYPASS_MODE_ID = 0x0B
IZZY_SENSOR_VENT_MODE_ID = 0x0C
IZZY_SENSOR_COVER_STATE_ID = 0x0D
IZZY_SENSOR_EFFICIENCY_ID = 0x0E
IZZY_SENSOR_DEFROST_STATE_ID = 0x0F
IZZY_SENSOR_EXTRACT_CORRECTION_STATE_ID = 0x10
IZZY_SENSOR_CF_EXTRACT_CORRECTION_ID = 0x11
IZZY_SENSOR_CF_SUPPLY_CORRECTION_ID = 0x12
IZZY_SENSOR_HUMIDITY_ID = 0x13
IZZI_SENSOR_PPM_STATE_ID = 0x14
IZZI_SENSOR_CF_EXHAUST_SPEED_STATE_ID = 0x15
IZZI_SENSOR_CF_SUPPLY_SPEED_STATE_ID = 0x16
IZZI_SENSOR_CURRENT_VENT_MODE_ID = 0x17
IZZI_SENSOR_SUPPLY_STATE_ID = 0x18
IZZI_SENSOR_EXTRACT_STATE_ID = 0x19
IZZI_SENSOR_HIGRO_CO2_STATUS_ID = 0x1a # msg
IZZI_SENSOR_HIGRO_CO2_STATE_ID = 0x1b # cmd