# Describes the format for available services
bypass_mode:
  description: Set bypass mode.
  fields:
    mode:
      description: Mode
      example: "auto, open, closed"

bypass_temp:
  description: Set bypass comfort temperature in auto mode.
  fields:
    temp:
      description: Temperature
      example: "23"

vent_custom_mode:
  description: Set ventilation custom mode.
  fields:
    mode:
      description: Mode
      example: "none, fireplace, open windows, cooker hood"

vent_preset_mode:
  description: Set ventilation preset mode.
  fields:
    mode:
      description: Mode
      example: "off, Speed-1, Speed-2, Speed-3, Ventilate, Fireplace, Away, Auto"

correction:
  description: Set extract fan correction.
  fields:
    value:
      description: Extract fan correction in range -50:50
      example: "10"

speed_raw:
  description: Set fans speed.
  fields:
    supply:
      description: Set supply fan custom speed.
      example: "40"
    extract:
      description: Set extract fan custom speed.
      example: "40"

cf_params:
  description: Set Constant flow module params.
  fields:
    supply:
      description: Set supply fan CF module param.
      example: "25.4"
    extract:
      description: Set extract fan CF module param.
      example: "25.5"
