  
# Describes the format for available services
bypass_mode:
  description: Set bypass mode.
  fields:
    mode:
      description: Mode setting
      example: "auto, open, closed"
      
bypass_temp:
  description: Set bypass comfort temperature in auto mode.
  fields:
    temp:
      description: Temperature setting
      example: "23"

vent_mode:
  description: Set ventilation special mode.
  fields:
    mode:
      description: Mode setting
      example: "none, fireplace, open windows"
